name: DockerHub to AWS ECR

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Login to Docker Hub
      run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

    - name: Pull Docker image from DockerHub
      run: docker pull therahul7777/timeoff-management-app:timeoff

    # - name: Build Docker image
    #   run: docker build -t iamrahul .  # Assuming Dockerfile is in the root directory

    - name: Tag Docker image for ECR
      run: docker tag iamrahul:latest public.ecr.aws/y6b7y1z6/iamrahul:latest

    - name: Push Docker image to AWS ECR
      run: |
        docker login --username AWS --password "${{ secrets.AWS_ACCESS_KEY_ID }}" public.ecr.aws/y6b7y1z6
        docker push public.ecr.aws/y6b7y1z6/iamrahul:latest


