name: my new ecr code
on:
  push:
    branches:
      - main
jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Dockerpull
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
          IMAGE_TAG: yadav-${{ github.run_id }}
          ECR_REPOSITERY: 342333476898.dkr.ecr.us-east-1.amazonaws.com
          ECR_IMAGE: github
          rahul: 44.211.44.187
          username: ${{ secrets.AWS_USERNAME }}

        run: |
          sudo docker build -t yadav .
          sudo docker run --name iamrahulyadavyvvbgg -d -p 7675:80 yadav
          aws ecr get-login-password --region us-est-1 | sudo docker login --username AWS --password-stdin $ECR_REPOSITERY
          sudo docker tag yadav:latest $ECR_REPOSITERY/$ECR_IMAGE:$IMAGE_TAG
          sudo docker push $ECR_REPOSITERY/$ECR_IMAGE:$IMAGE_TAG
          ssh -i ${{ secrets.SSH_PRIVATE_KEY }} $username@$rahul "echo 'Connected to AWS server.'"
          sudo docker pull $ECR_REPOSITERY/$ECR_IMAGE:$IMAGE_TAG
