name: Dyadav

on:
  push:
    branches:
      - main


jobs:
  build_and_push:
    runs-on: self-hosted
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Pull Docker image from DockerHub
        env:
        IMAGE_TAG: ${{github.run_id}}
      
        run: |
          sudo docker pull therahul7777/timeoff-management-app:timeoff 
       
      - name: Login to AWS ECR
        run: |
          aws ecr get-login-password --region us-east-1 | sudo docker login --username AWS --password-stdin 654654507153.dkr.ecr.us-east-1.amazonaws.com

      - name: Tag Docker image for ECR
        run: |
         sudo docker tag therahul7777/timeoff-management-app:timeoff 654654507153.dkr.ecr.us-east-1.amazonaws.com/iamrahul:$IMAGE_TAG
         
      - name: Push Docker image to AWS ECR
        run: |
         sudo docker push 654654507153.dkr.ecr.us-east-1.amazonaws.com/iamrahul:$IMAGE_TAG
