name: mynew ecr

on:
  push:
    branches:
      - main


jobs:
  build_and_push:
    runs-on: self-hosted
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        
      - name: Dockerpull
        env:
          IMAGE_TAG: yadav-${{ github.run_id }}
        run: |
         sudo docker build -t rahul . 
         sudo docker run --name yaaaaa -d -p 5565:80 rahul
         aws ecr get-login-password --region us-east-1 | sudo docker login --username AWS --password-stdin 654654507153.dkr.ecr.us-east-1.amazonaws.com
         sudo docker tag rahul:latest 654654507153.dkr.ecr.us-east-1.amazonaws.com/rahulsadu:IMAGE_TAG
         sudo  docker push 654654507153.dkr.ecr.us-east-1.amazonaws.com/rahulsadu:IMAGE_TAG
