name: Docker Build and Push

on:
  push:
    branches:
      - main

env:
  ACTIONS_RUNNER_DEBUG: true

jobs:
  build_and_push:
    runs-on: self-hosted
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install Docker
        run: |
          sudo apt-get update && sudo apt-get install -y docker.io
          sudo usermod -aG docker $USER
          sudo chmod 777 /var/run/docker.sock

      - name: Login to DockerHub
        run: |
          echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" 

      - name: Pull Docker image from DockerHub
        run: |
          docker pull therahul7777/timeoff-management-app:timeoff || true

      - name: Build Docker image
        run: |
         cd timeoff-management-app
          docker build -t iam .
        
      - name: Install AWS CLI
        run: |
          sudo apt-get update && sudo apt-get install -y awscli
          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws configure set default.region us-east-1

      - name: Login to AWS ECR
        run: |
          aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws/y6b7y1z6

      - name: Tag Docker image for ECR
        run: |
          docker tag iam:latest public.ecr.aws/y6b7y1z6/iamrahul:latest

      - name: Push Docker image to AWS ECR
        run: |
          docker push public.ecr.aws/y6b7y1z6/iamrahul:latest
