name: Docker Build and Push

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Login to Docker Hub
      run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

    - name: Build and tag Docker image
      run: |
        docker build -t docker build -t iamrahul .
        docker tag docker pull therahul7777/timeoff-management-app:timeoff docker pull therahul7777/timeoff-management-app:${{ github.sha }}

    - name: Push Docker image to Docker Hub
      run: docker push docker pull therahul7777/timeoff-management-app

    - name: Login to AWS ECR
      run: aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws/y6b7y1z6
    - name: Tag Docker image for ECR
      run: docker tag iamrahul:latest public.ecr.aws/y6b7y1z6/iamrahul:latest

    - name: Push Docker image to AWS ECR
      run: docker push public.ecr.aws/y6b7y1z6/iamrahul:latest
