name: mynew ecr

on:
  push:
    branches:
      - main


jobs:
  build_and_push:
    runs-on: self-hosted
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        
      - name: Dockerpull
        run: |
         sudo docker build -t rahul . 
         sudo docker run --name yadavyadavdf -d -p 5555:80 rahul
