name: my new ecr code

on:
  push:
    branches:
      - main


jobs:
  build_and_push:
    runs-on: self-hosted
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        
      - name: Dockerpull
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
          IMAGE_TAG: yadav-${{ github.run_id }}
          ECR_REPOSITERY: 654654507153.dkr.ecr.us-east-1.amazonaws.com
          ECR_IMAGE: iamrahul
          
        run: |
         sudo docker build -t rahul . 
         sudo docker run --name yadavjiiii -d -p 7885:80 rahul
         aws ecr get-login-password --region us-east-1 | sudo docker login --username AWS --password-stdin $ECR_REPOSITERY
         sudo docker tag rahul:latest $ECR_REPOSITERY/$ECR_IMAGE:$IMAGE_TAG
         sudo  docker push $ECR_REPOSITERY/$ECR_IMAGE:$IMAGE_TAG
