name: my new gcp code

on:
  push:
    branches:
      - main

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      # Log in to Google Container Registry
      - name: Log in to GCR
        uses: docker/login-action@v2
        with:
          registry: gcr.io
          username: _json_key
          password: ${{ secrets.GCP_SA_KEY }}

      # Build Docker image
      - name: Build Docker image
        run: docker build -t gcr.io/testing-gcp-ops/suresh:latest .

      # Push Docker image to GCR
      - name: Push Docker image to GCR
        run: docker push gcr.io/testing-gcp-ops/suresh:latest
