name: my new ecr code
on:
  push:
    branches:
      - main
jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: Login to Amazon ECR Private
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
      
      - name: executing remote ssh commands using ssh key
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.AWS_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.AWS_SSH_PORT }}
          script: whoami
      - name: Install AWS CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y awscli
      - name: Dockerpull
        env:
          IMAGE_TAG: yadav-${{ github.run_id }}
          ECR_REPOSITORY: 342333476898.dkr.ecr.us-east-1.amazonaws.com
          ECR_IMAGE: github
          
          host: ${{ secrets.HOST }}
          username: ${{ secrets.AWS_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.AWS_SSH_PORT }}
          script: whoami
        run: |
          docker build -t $ECR_REPOSITORY/$ECR_IMAGE:$IMAGE_TAG .
          echo "Pushing image to ECR..."
          docker push $ECR_REPOSITORY/$ECR_IMAGE:$IMAGE_TAG
          echo "::set-output name=image::$ECR_REPOSITORY/$ECR_IMAGE:$IMAGE_TAG"
      
          ssh -i ${{ secrets.SSH_PRIVATE_KEY }} ubuntu@44.211.44.187 "echo 'Connected to AWS server.'"
          sudo apt-get install awscli -y
          sudo docker pull $ECR_REPOSITORY/$ECR_IMAGE:$IMAGE_TAG
